#!/usr/bin/ruby
require 'optparse'
options = {:host => '0.0.0.0', :port => 3000, :interactive => false, :auto_lock => false}
op = OptionParser.new do |opts|
  opts.banner = "Usage: fsclient [options] <lock | token command [command_args ... ]>"
  opts.on("--host=HOST", String, "Server host (default is 0.0.0.0)") {|h| options[:host] = h}
  opts.on("--port=PORT", Integer, "Server port (default is 3000)") {|p| options[:port] = p}
  opts.on("-i","--interactive", "Interactive mode") {|i| options[:interactive] = true}
  opts.on("-a","--auto-lock", "Auto lock in interactive mode") {|i| options[:auto_lock] = true}

  opts.separator ""
  opts.separator "Common options:"

  opts.on_tail("-h", "--help", "Show this message") do
    puts opts
    exit
  end
end
op.parse!

if !options[:interactive] && ARGV.size < 1
	puts op
	exit
end

# Setup root dir
ROOT_DIR = File.dirname(__FILE__)

# Start the client
require ROOT_DIR + '/lib/client'
Client.instance.start(options[:host], options[:port], options[:auto_lock], options[:interactive])
