#!/usr/bin/ruby
require 'socket'
require 'optparse'
require File.dirname(__FILE__) + '/lib/fsterm2'

options = {:host => '0.0.0.0', :port => 3000, :interactive => false, :auto_lock => false}
op = OptionParser.new do |opts|
  opts.banner = "Usage: fsterm2 [options] <lock | token command [command_args ... ]>"
  opts.on("--host=HOST", String, "Server host (default is 0.0.0.0)") {|h| options[:host] = h}
  opts.on("--port=PORT", Integer, "Server port (default is 3000)") {|p| options[:port] = p}
  opts.on("-i","--interactive", "Interactive mode") {|i| options[:interactive] = true}
  opts.on("-a","--auto-lock", "Auto lock in interactive mode") {|i| options[:auto_lock] = true}

  opts.separator ""
  opts.separator "Common options:"

  opts.on_tail("-h", "--help", "Show this message") do
    puts opts
    exit
  end

  opts.on_tail("--version", "Show version") do
    FSTerm2.author_version
    exit
  end
end
op.parse!

if !options[:interactive] && ARGV.size < 1
	puts op
	exit
end

begin
	TCPSocket.open(options[:host],options[:port]) do |s|
		f = FSTerm2.new(s, options[:auto_lock])
		if options[:interactive]
			f.interactive_loop
		else
			f.single_command(ARGV.join(' '))
		end
	end
rescue Errno::ECONNREFUSED => e
	puts 'Could not connect to server'
end
