#!/usr/bin/ruby
require 'optparse'
require 'rubygems'
require 'json'
require 'open3'

PLANETS = %w( mercury venus mars jupiter saturn uranus neptune )

op = OptionParser.new do |opts|
  opts.banner = "Usage: blast token planet ray_size"
  opts.separator "Description: Shoot a laser ray towards a planet of your choice"
  opts.separator "Arguments:"
  opts.separator "\tplanet    (string)    #{PLANETS.join(', ')}"
  opts.separator "\tray_size  (integer)   1-5 where 1 stings, 3 hurts and 5 evaporates"
end
op.parse!

if(ARGV.length != 3)
	puts("Not enough arguments. (#{ARGV.map{|a| "'#{a}'"}.join(",")}) given, 3 needed")
	exit(2)
end

token = ARGV[0]
planet = ARGV[1]
ray_size = ARGV[2]

if(planet.downcase == "earth")
	puts "Traitor!! All your base are belong to us now!"
	exit(99)
end

if(planet.downcase == "pluto")
	puts "Pluto is NOT a planet... NOT A PLANET!"
	exit(98)
end

unless(PLANETS.include?(planet.downcase))
	puts("Unknown planet")
	exit(3)
end

unless((1..5).include?(ray_size.to_i))
	puts("Invalid ray size")
	exit(3)
end

fsclient = File.dirname(__FILE__) + "/../client/fsclient"

stdin, stdout, stderr = Open3.popen3(fsclient, token, "reset")
raw = stdout.readlines.join

response = JSON.parse(raw);

if response["status"] == 0
  puts "Ray blasted at #{planet} with ray size #{ray_size}"
else
  puts "Blast failed: #{response["body"]}"
end

exit(response["status"])
