#!/usr/bin/ruby
require 'optparse'
require 'rubygems'
require 'json'
require 'open3'

op = OptionParser.new do |opts|
  opts.banner = "Usage: reset token"
  opts.separator "Description: Reset the sattelite (Client Script)"
end
op.parse!

token = ARGV[0]
fsclient = File.dirname(__FILE__) + "/../../client/fsclient"

stdin, stdout, stderr = Open3.popen3(fsclient, token, "reset")
raw = stdout.readlines.join
response = JSON.parse(raw);

if response["status"] == 0
  puts "Reset succeeded"
else
  puts "Reset failed"
end

exit(response["status"])
