#!/usr/bin/ruby
require 'optparse'
require 'rubygems'
require 'json'
require 'open3'

op = OptionParser.new do |opts|
  opts.banner = "Usage: reset token"
  opts.separator "Description: Reset the sattelite"
end
op.parse!

token = ARGV[0]

stdin, stdout, stderr = Open3.popen3("fsclient", token, "reset")
raw = stdout.readlines.join
response = JSON.parse(raw);

if response["status"] == 0
	5.times do |n|
		sleep(1)
	  puts "Reset succeeded. #{20*(n+1)}% done!"
  end
else
  puts "Reset failed"
end

exit(response["status"])
