#!/usr/bin/ruby
require 'optparse'

options = {:host => '0.0.0.0', :port => 3000, :logfile => STDOUT}
op = OptionParser.new do |opts|
  opts.banner = "Usage: fsserver [options]"
  opts.on("--host=HOST", String, "Server host") {|h| options[:host] = h}
  opts.on("--port=PORT", Integer, "Server port") {|p| options[:port] = p}
  opts.on("--logfile=LOGFILE", String, "Logfile to be used") {|l| options[:logfile] = l}

  opts.separator ""
  opts.separator "Common options:"

  opts.on_tail("-h", "--help", "Show this message") do
    puts opts
    exit
  end

  opts.on_tail("--version", "Show version") do
		puts "FSDaemon Version #{Server::VERSION}"
		puts "Kasper Bjørn Nielsen (s052808@student.dtu.dk)"
    exit
  end
end
op.parse!

# Setup root dir
ROOT_DIR = File.dirname(__FILE__)

# Setup log
require ROOT_DIR+"/lib/fs_logger"
$LOG = FSLogger.new(options[:logfile])

# Run server
require ROOT_DIR+"/lib/server"
Server.instance.start(options[:host], options[:port])
