#!/usr/bin/ruby
require 'optparse'
require 'rubygems'
require 'serialport'

options = {
	:host => '0.0.0.0',
	:port => 3000,
	:logfile => STDOUT,
	:timeout => 30
}

op = OptionParser.new do |opts|
  opts.banner = "Usage: fsserver [options]"
  opts.on("--host=HOST", String, "('0.0.0.0')") 									{|o| options[:host] = o}
  opts.on("--port=PORT", Integer, "(3000)") 											{|o| options[:port] = o}
  opts.on("--timeout=TIMEOUT", Integer, "(30)") 									{|o| options[:timeout] = o}
  opts.on("--logfile=LOGFILE", String, "(stdout)") 								{|o| options[:logfile] = o}

  opts.separator ""
  opts.separator "Common options:"

  opts.on_tail("-h", "--help", "Show this message") do
    puts opts
    exit
  end

  opts.on_tail("--version", "Show version") do
		puts "FSServer Version 1.0"
		puts "Kasper Bjørn Nielsen (s052808@student.dtu.dk)"
    exit
  end
end
op.parse!

# Setup root dir
ROOT_DIR = File.dirname(__FILE__)

# Setup log
require ROOT_DIR+"/lib/logger"
$LOG = FSLogger.new(options[:logfile])

# Setup thread abort
Thread.abort_on_exception = true

# Run server
require ROOT_DIR+"/lib/server"
Server.instance.start(options)
