#!/usr/bin/ruby

fsterm2 = File.dirname(__FILE__) + "/../client/fsterm2"

token = `#{fsterm2} lock_fs_term`.gsub("\n", "")
puts "Token: #{token}"

if `#{fsterm2} #{token} execute 234234` =~ /Execute/
  puts "Execute succeeded"
  if `#{fsterm2} #{token} reset` =~ /Reset/
    puts "Reset succeeded"
  else
    puts "Reset failed"
  end
else
  puts "Execute failed"
end

puts `#{fsterm2} #{token} unlock_fs_term`