#!/usr/bin/ruby
require 'optparse'
require 'rubygems'
require 'json'
require 'open3'

op = OptionParser.new do |opts|
  opts.banner = "Usage: upload token filepath address"
  opts.separator "Description: Upload a file to an address in the satellites memory"
  opts.separator "Arguments:"
  opts.separator "\tfilepath (string)"
  opts.separator "\taddress (hexadecimal)"
end
op.parse!

if ARGV.length != 3
	puts "Not enough arguments"
	exit(2)
end

token = ARGV[0]
filepath = ARGV[1]
address = ARGV[2]

stdin, stdout, stderr = Open3.popen3("fsclient", token, "upload", filepath, address)
raw = stdout.readlines.join

response = JSON.parse(raw);
if response['status'] == 0
	puts "Upload OK"
else
	puts "Upload Failed"
end
exit(response['status']);
