#!/usr/bin/ruby
token = ARGV[0]
#token = `fsterm2 lock`.gsub("\n",'').gsub("\r",'')

puts "Token: #{token}"

if `fsterm2 #{token} execute #{ARGV[1]}` =~ /Execute/
  puts "Execute succeeded"
  if `fsterm2 #{token} reset` =~ /Reset/
    puts "Reset succeeded"
    exit(0)
  else
    puts "Reset failed"
    exit(1)
  end
else
  puts "Execute failed"
	exit(1)
end
