#!/usr/bin/ruby
require 'optparse'
op = OptionParser.new do |opts|
  opts.banner = "Usage: reset_and_execute address"
  opts.separator "Description: Reset the sattelite and execute from address."
  opts.separator "Arguments:"
  opts.separator "\taddress (hexadecimal)"
end
op.parse!

token = ARGV[0]
address = ARGV[1]

if `fsclient #{token} reset` =~ /Reset/
  puts "Reset succeeded"
	if `fsclient #{token} execute #{address}` =~ /Execute/
		puts "Execute succeeded"
	else
		puts "Execute failed"
		exit(1)
	end
  exit(0)
else
  puts "Reset failed"
  exit(1)
end
